// Valori di default usati finché l'admin/TEST/DEMO non configura i template
// globali (settings.templates) dal pannello. Porting 1:1 dal file originale.

export const companyInfoText = `International Food Pivot Srl
Sede legale ed operativa
Piazza Duca D'Aosta, 12
20124 Milano – Italia
Partita IVA 11514530960
ordini@italianfoodpivot.it
amministrazione@italianfoodpivot.it
PEC internationalfoodpivot@legalmail.it
Codice SDI SUBM70N
Tel. +39 02 82197510`;

export const ALLERGENI_DETTAGLIATI = [
  { id: 0, it: "Cereali contenenti glutine (grano, segale, orzo, avena, farro, kamut o i loro ceppi ibridati) e prodotti derivati", en: "Cereals containing gluten (wheat, rye, barley, oats, spelt, kamut or their hybridised strains) and products thereof", fr: "Céréales contenant du gluten (blé, seigle, orge, avoine, épeautre, kamut ou leurs souches hybridées) et produits à base de ces céréales", es: "Cereales que contengan gluten (trigo, centeno, cebada, avena, espelta, kamut o sus variedades híbridas) y productos derivados" },
  { id: 1, it: "Crostacei e prodotti a base di crostacei", en: "Crustaceans and products thereof", fr: "Crustacés et produits à base de crustacés", es: "Crustáceos y productos a base de crustáceos" },
  { id: 2, it: "Uova e prodotti a base di uova", en: "Eggs and products thereof", fr: "Œufs et produits à base d'œufs", es: "Huevos y productos a base de huevo" },
  { id: 3, it: "Pesce e prodotti a base di pesce", en: "Fish and products thereof", fr: "Poissons et produits à base de poissons", es: "Pescado y productos a base de pescado" },
  { id: 4, it: "Arachidi e prodotti a base di arachidi", en: "Peanuts and products thereof", fr: "Arachides et produits à base d'arachides", es: "Cacahuetes y productos a base de cacahuetes" },
  { id: 5, it: "Soia e prodotti a base di soia", en: "Soybeans and products thereof", fr: "Soja et produits à base de soja", es: "Soja y productos a base de soja" },
  { id: 6, it: "Latte e prodotti a base di latte (incluso lattosio)", en: "Milk and products thereof (including lactose)", fr: "Lait et produits à base de lait (y compris le lactose)", es: "Leche y sus derivados (incluida la lactosa)" },
  { id: 7, it: "Frutta a guscio (mandorle, nocciole, noci, noci di acagiù, noci di pecan, noci del Brasile, pistacchi, noci macadamia) e prodotti derivati", en: "Nuts, namely: almonds, hazelnuts, walnuts, cashews, pecan nuts, Brazil nuts, pistachio nuts, macadamia and products thereof", fr: "Fruits à coque, à savoir: amandes, noisettes, noix, noix de cajou, noix de pécan, noix du Brésil, pistaches, noix de Macadamia et produits à base de ces fruits", es: "Frutos de cáscara, es decir: almendras, avellanas, nueces, anacardos, pacanas, nueces de Brasil, alfóncigos, nueces macadamia y productos derivados" },
  { id: 8, it: "Sedano e prodotti a base di sedano", en: "Celery and products thereof", fr: "Céleri et produits à base de céleri", es: "Apio y productos derivados" },
  { id: 9, it: "Senape e prodotti a base di senape", en: "Mustard and products thereof", fr: "Moutarde et produits à base de moutarde", es: "Mostaza y productos derivados" },
  { id: 10, it: "Semi di sesamo e prodotti a base di semi di sesamo", en: "Sesame seeds and products thereof", fr: "Graines de sésame et produits à base de graines de sésame", es: "Granos de sésamo y productos a base de granos de sésamo" },
  { id: 11, it: "Anidride solforosa e solfiti (in concentrazioni superiori a 10 mg/kg o 10 mg/litro espressi come SO2 totale)", en: "Sulphur dioxide and sulphites at concentrations of more than 10 mg/kg or 10 mg/litre in terms of the total SO2", fr: "Anhydride sulfureux et sulfites en concentrations de plus de 10 mg/kg ou 10 mg/litre en termes de SO2 total", es: "Dióxido de azufre y sulfitos en concentraciones superiores a 10 mg/kg o 10 mg/litro en términos de SO2 total" },
  { id: 12, it: "Lupini e prodotti a base di lupini", en: "Lupin and products thereof", fr: "Lupin et produits à base de lupin", es: "Altramuces y productos a base de altramuces" },
  { id: 13, it: "Molluschi e prodotti a base di molluschi", en: "Molluscs and products thereof", fr: "Mollusques et produits à base de mollusques", es: "Moluscos y productos a base de moluscos" }
];

export const DEFAULT_IMPEGNI_A = [
  { id: 'impA_0', it: "1) L'Azienda Fornitrice si impegna ad utilizzare esclusivamente ingredienti, additivi e coadiuvanti tecnologici esenti da OGM o da derivati di OGM, in stretta ottemperanza ai Regolamenti CE 1829/2003 e 1830/2003, impegnandosi inoltre a comunicare tempestivamente in forma scritta qualsiasi futura variazione a tale stato.", en: "1) The Supplying Company undertakes to exclusively use ingredients, additives, and processing aids free from GMOs or GMO derivatives, in strict compliance with EC Regulations 1829/2003 and 1830/2003, and also undertakes to promptly communicate in writing any future change to this status.", fr: "1) L'Entreprise Fournisseur s'engage à utiliser exclusivement des ingrédients, additifs et auxiliaires technologiques exempts d'OGM ou de dérivés d'OGM, en stricte conformité avec les Règlements CE 1829/2003 e 1830/2003, s'engageant également à communiquer rapidement par écrit tout changement futur de ce statut.", es: "1) La Empresa Proveedora se compromete a utilizar exclusivamente ingredientes, aditivos y coadyuvantes tecnológicos libres de OGM o derivados de OGM, en estricto cumplimiento de los Reglamentos CE 1829/2003 y 1830/2003, comprometiéndose también a comunicar rápidamente por escrito cualquier cambio futuro en este estado." },
  { id: 'impA_1', it: "2) L'Azienda Fornitrice dichiara di aver implementato e di mantenere attive procedure e precauzioni preventive, integrate nel proprio sistema di autocontrollo e nelle procedure aziendali, finalizzate a prevenire e ridurre al minimo il rischio di commistione/contaminazione involontaria con materiali contenenti OGM durante i processi di stoccaggio, lavorazione e trasporto, in conformità ai Regolamenti (CE) 1829/2003 e 1830/2003.", en: "2) The Supplying Company declares that it has implemented and maintains active preventive procedures and precautions, integrated into its self-control system and corporate procedures, aimed at preventing and minimizing the risk of involuntary mixing/contamination with materials containing GMOs during storage, processing and transport processes, in compliance with Regulations (EC) 1829/2003 and 1830/2003.", fr: "2) L'entreprise fournisseuse déclare avoir mis en œuvre et maintenir des procédures et des précautions préventives, intégrées dans son système d'autocontrôle et ses procédures d'entreprise, visant à prévenir et à minimiser le risque de mélange/contamination involontaire avec des matériaux contenant des OGM lors des processus de stockage, de transformation et de transport, conformément aux règlements (CE) 1829/2003 et 1830/2003.", es: "2) La Empresa Proveedora declara haber implementado y mantener procedimientos y precauciones preventivas, integradas en su sistema de autocontrol y procedimientos corporativos, con el objetivo de prevenir y minimizar el riesgo de mezcla/contaminación involuntaria con materiales que contienen OGM durante los procesos de almacenamiento, procesamiento y transporte, de acuerdo con los Reglamentos (CE) 1829/2003 y 1830/2003." },
  { id: 'impA_2', it: "3) L'Azienda Fornitrice dichiara di predisporre, aggiornare regolarmente e condividere un'analisi dei pericoli igienico-sanitari (HACCP) e di applicare un sistema di qualifica e monitoraggio dei propri sub-fornitori, mediante procedure documentate e controlli periodici, al fine di assicurare la conformità e la sicurezza dei prodotti lungo la filiera a monte.", en: "3) The Supplying Company declares to prepare, regularly update and share an analysis of hygienic-sanitary hazards (HACCP) and to apply a qualification and monitoring system of its sub-suppliers, through documented procedures and periodic checks, in order to ensure the compliance and safety of products along the upstream supply chain.", fr: "3) L'entreprise fournisseuse déclare préparer, mettre à jour régulièrement et partager une analyse des risques hygiéno-sanitaires (HACCP) et appliquer un système de qualification et de suivi de ses sous-traitants, au moyen de procédures documentées et de contrôles périodiques, afin de garantir la conformité et la sécurité des produits tout au long de la chaîne d'approvisionnement en amont.", es: "3) La Empresa Proveedora declara preparar, actualizar regularmente y compartir un análisis de peligros higiénico-sanitarios (HACCP) y aplicar un sistema de calificación y monitoreo de sus subproveedores, mediante procedimientos documentados y controles periódicos, con el fin de asegurar el cumplimiento y la seguridad de los productos a lo largo de la cadena de suministro ascendente." },
  { id: 'impA_3', it: "4) L'Azienda Fornitrice dichiara di applicare rigorosamente tutte le procedure, le separazioni temporali/spaziali e i protocolli di sanificazione validati previsti dal proprio piano HACCP per scongiurare il rischio di cross-contaminazione accidentale da ALLERGENI (Reg. UE 1169/2011) tutelando il consumatore finale.", en: "4) The Supplying Company declares to strictly apply all the procedures, temporal/spatial separations, and validated sanitization protocols foreseen by its HACCP plan to prevent the risk of accidental cross-contamination by ALLERGENS (EU Reg. 1169/2011) protecting the final consumer.", fr: "4) L'Entreprise Fournisseur déclare appliquer rigoureusement toutes les procédures, séparations temporelles/spatiales et protocoles de nettoyage validés prévus par son plan HACCP pour prévenir le risque de contamination croisée accidentelle par des ALLERGÈNES (Règ. UE 1169/2011) protégeant le consommateur final.", es: "4) La Empresa Proveedora declara aplicar rigurosamente todos los procedimientos, separaciones temporales/espaciales y protocolos de limpieza validados previstos por su plan APPCC para prevenir el riesgo de contaminación cruzada accidental por ALÉRGENOS (Reg. UE 1169/2011) protegiendo al consumidor final." }
];

export const DEFAULT_IMPEGNI_B = [
  { id: 'validazioneProd', title_it: "Validazione dei Processi Produttivi", desc_it: "L'Azienda Fornitrice garantisce formalmente che tutti i processi di produzione, confezionamento, stoccaggio e manipolazione sono regolarmente validati, costantemente monitorati e documentati secondo le normative igienico-sanitarie vigenti (Pacchetto Igiene) e nel rispetto dei parametri definiti dai severi standard di certificazione volontaria adottati.", title_en: "Validation of Production Processes", desc_en: "The Supplying Company formally guarantees that all production, packaging, storage, and handling processes are regularly validated, constantly monitored, and documented according to the hygiene and sanitary regulations in force (Hygiene Package) and in compliance with the parameters defined by the strict voluntary certification standards adopted.", title_fr: "Validation des Processus de Production", desc_fr: "L'Entreprise Fournisseur garantit formellement que tous processus de production, conditionnement, stockage et manipulation sont régulièrement validés, constamment surveillés et documentés conformément à la réglementation en matière d'hygiène en vigueur (Paquet Hygiène) et dans le respect des paramètres définis par les normes de certification volontaires strictes adoptées.", title_es: "Validación de los Procesos de Producción", desc_es: "La Empresa Proveedora garantiza formalmente que todos los procesos de producción, envasado, almacenamiento y manipulación se validan regularmente, se supervisan constantemente y se documentan de acuerdo con las normativas higiénico-sanitarias vigentes (Paquete de Higiene) y en cumplimiento de los parámetros definidos por los estrictos estándares de certificación voluntaria adoptados." },
  { id: 'validazioneTras', title_it: "Sicurezza, Igiene e Trasporti a Temperatura Controllata", desc_it: "L'Azienda Fornitrice garantisce che i mezzi di trasporto utilizzati per le consegne in entrata e in uscita rispettano i più rigidi requisiti igienico-sanitari (HACCP). Viene garantito senza interruzioni il mantenimento della catena del freddo o delle temperature specifiche richieste per la conservazione ottimale del prodotto. I veicoli sono inoltre assoggettati a regolari e documentati piani di pulizia e sanificazione.", title_en: "Safety, Hygiene, and Temperature-Controlled Transport", desc_en: "The Supplying Company guarantees that the means of transport used for incoming and outgoing deliveries meet the strictest hygiene and sanitary requirements (HACCP). The maintenance of the cold chain or specific temperatures required for optimal product conservation is guaranteed without interruption. Vehicles are also subjected to regular and documented cleaning and sanitization plans.", title_fr: "Sécurité, Hygiène et Transport sous Température Contrôlée", desc_fr: "L'Entreprise Fournisseur garantit que les moyens de transport utilisés pour les livraisons entrantes et sortantes respectent les exigences hygiéno-sanitaires les plus strictes (HACCP). Le maintien de la chaîne du froid ou des températures spécifiques requises pour une conservation optimale du produit est garanti sans interruption. Les véhicules sont également soumis à des plans de nettoyage et d'assainissement réguliers et documentés.", title_es: "Seguridad, Higiene y Transporte a Temperatura Controlada", desc_es: "La Empresa Proveedora garantiza que los medios de transporte utilizados para las entregas entrantes y salientes cumplen con los requisitos higiénico-sanitarios más estrictos (APPCC). Se garantiza sin interrupción el mantenimiento de la cadena de frío o de las temperaturas específicas requeridas para la conservación óptima del producto. Los vehículos también están sujetos a planes de limpieza y desinfección regulares y documentados." },
  { id: 'rintracciabilita', title_it: "Rintracciabilità Integrale (Reg. CE 178/2002)", desc_it: "L'Azienda Fornitrice garantisce l'implementazione e l'efficacia di un sistema strutturato di rintracciabilità (in conformità al Regolamento CE 178/2002), in grado di identificare biunivocamente e in qualsiasi momento il lotto specifico di materia prima, del materiale di imballaggio primario e del prodotto finito. Si garantisce l'esecuzione di simulazioni di ritiro/richiamo dal mercato con cadenza almeno annuale.", title_en: "Full Traceability (EC Reg. 178/2002)", desc_en: "The Supplying Company guarantees the implementation and effectiveness of a structured traceability system (in compliance with EC Reg. 178/2002), capable of uniquely identifying at any time the specific batch of raw material, primary packaging material, and finished product. The execution of market withdrawal/recall simulations is guaranteed at least annually.", title_fr: "Traçabilité Intégrale (Règ. CE 178/2002)", desc_fr: "L'Entreprise Fournisseur garantit la mise en œuvre et l'efficacité d'un système de traçabilité structuré (conformément au Règlement CE 178/2002), capable d'identifier de manière univoque et à tout moment le lot spécifique de matière première, de matériau d'emballage primaire et de produit fini. L'exécution de simulations de retrait/rappel du marché est garantie au moins annuellement.", title_es: "Trazabilidad Integral (Reg. CE 178/2002)", desc_es: "La Empresa Proveedora garantiza la implementación y eficacia de un sistema de trazabilidad estructurado (de conformidad con el Reg. CE 178/2002), capaz de identificar de forma inequívoca y en cualquier momento el lote específico de materia prima, material de embalaje primario y producto terminado. Se garantiza la ejecución de simulacros de retirada/recuperación del mercado al menos anualmente." }
];

export const DEFAULT_CERTIFICAZIONI = [
  { id: 'ifs', type: 'IFS Food', fileName: '', fileUrl: '', expiry: '' },
  { id: 'brc', type: 'BRCGS Food', fileName: '', fileUrl: '', expiry: '' },
  { id: 'bio', type: 'Certificazione Biologica', fileName: '', fileUrl: '', expiry: '' }
];
